name: ldabot
version: 0.1.0.0
author: Alexander Shestakov
copyright: 2020 Alexander Shestakov
maintainer: a.shestakov@itransition.com
library:
  source-dirs: src
  ghc-options:
  - -Wall
default-extensions:
- OverloadedStrings
dependencies:
- base >= 4.7 && < 5

- freer-simple
- aeson
- data-default

- text
- vector
- bytestring
- neat-interpolation

- ldap-client

- http-client
- http-client-tls

- servant-server
- servant-client

- wai-extra
- warp
tests:
  ldabot-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldabot

    - hspec
    - hspec-discover
    - validity
    - validity-vector
    - genvalidity
    - genvalidity-vector
    - genvalidity-text
    - genvalidity-hspec
    - QuickCheck
    - silently
executables:
  ldabot-prod:
    when:
    - condition: os(darwin)
      buildable: false
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -static
    - -optl-static
    - -optl-pthread
    - -fPIC
    - -optc-Os
    - -O2
    - -threaded
    - -rtsopts=none
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ldabot
  ldabot-exe:
    when:
    - condition: os(linux)
      buildable: false
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ldabot