name: ldabot
version: 0.1.0.0
author: Alexander Shestakov
copyright: 2020 Alexander Shestakov
maintainer: a.shestakov@itransition.com
library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - base >= 4.7 && < 5
  - vector
  - ldap-client
  - hoist-error
  - aeson
  - text
  - bytestring
  - http-client
  - http-client-tls
  - servant-server
  - servant-client
  - wai-extra
  - warp
  - transformers
tests:
  ldabot-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldabot
    - hspec
    - validity
    - validity-text
    - genvalidity
    - genvalidity-text
    - genvalidity-hspec
executables:
  ldabot-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ldabot
    - base >= 4.7 && < 5
