name: ldabot
version: 0.1.0.0
author: Alexander Shestakov
copyright: 2020 Alexander Shestakov
maintainer: a.shestakov@itransition.com
library:
  source-dirs: src
  ghc-options:
  - -Wall
default-extensions:
- OverloadedStrings
dependencies:
- base >= 4.7 && < 5

- aeson
- data-default

- text
- vector
- bytestring
- neat-interpolation

- ldap-client

- http-client
- http-client-tls

- servant-server
- servant-client

- wai-extra
- warp

- mtl
- hoist-error

- hspec
- validity
- validity-vector
- genvalidity
- genvalidity-vector
- genvalidity-text
- genvalidity-hspec
- QuickCheck
- silently
tests:
  ldabot-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldabot
executables:
  ldabot-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ldabot
