name: ldabot
version: 0.2.0.0
author: Alexander Shestakov
copyright: 2020 Itransition
maintainer: a.shestakov@itransition.com
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fplugin=Polysemy.Plugin
default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- LambdaCase
- MonoLocalBinds
- NamedFieldPuns
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
dependencies:
- base >= 4.7 && < 5

- polysemy >= 1.2.3.0
- polysemy-plugin

- aeson
- data-default
- text
- bytestring
- containers
- neat-interpolation

- ldap-client

- http-client
- http-client-tls

- servant-server
- servant-client

- wai-extra
- warp
tests:
  ldabot-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldabot

    - hspec
    - hspec-discover
    - QuickCheck
    - quickcheck-instances
    - quickcheck-arbitrary-template
    - silently
executables:
  ldabot-prod:
    when:
    - condition: os(darwin)
      buildable: false
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -static
    - -optl-static
    - -optl-pthread
    - -fPIC
    - -optc-Os
    - -O2
    - -threaded
    - -rtsopts=none
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ldabot
  ldabot-exe:
    when:
    - condition: os(linux)
      buildable: false
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldabot